# https://taskfile.dev

version: '3'

vars:
  BIN: goraytracer
  OUTFILE: out.ppm

tasks:
  default:
    dir: cmd/"{{.BIN}}"
    cmds:
      - rm -f "{{.BIN}}"
      - go build .
      - rm -f "{{.OUTFILE}}"
      - ./"{{.BIN}}" > ../../"{{.OUTFILE}}"
